### ISSUE TITLE
FTB Unstable 3.0.18 - Server Crash

### ISSUE THREAD

**Issue by cauliflower69** [LatvianModder/FTBLib#16]
Playing on a dedicated server and it crashed with this http://pastebin.com/jR7S2Hys on update

**Comment by LatvianModder** [comment]
Ah, the good ol' FTBUChunkEventHandler

**Comment by killerjerick** [comment]
Having the exact same problem, any solution?

**Comment by killerjerick** [comment]
Nvm, fixed it by disabling both FTBL and FTBU, starting the server and then re-enabling them, it happened when I used MCEDIT to delete a corrupted block.
