### ISSUE TITLE
Sync minetweaker Recipes not correctly - 1.7.10-1.0.17.4

### ISSUE THREAD

**Issue by DaNeo61** [LatvianModder/FTBLib#17]
Hello,

I Created a private modpack for friends with this and added New Scripts in a setting called extreme if i set up the server with extreme it will load them all and the players have the new recipes

Version 1.7.10-1.0.17.4
Forge 1614

Folders and Configs are correct and console says they get loaded only the recipes are not displayed correctly only after a "/mt reload" and it will hold it

If a player reconnect to the server it shows the normal Crafting recipes again there are not craftable but you will see not the correct recipes to craft until the server reloads them over "/mt reload"

Scripts are only on Server not on client because i dont want to update the whole modpack everytime after i changed a recipe.

**Comment by LatvianModder** [comment]
Do you have FTBTweaks installed? If you do, /mt reload wont work, nor will placing files in /scripts folder. Instead you should place them in /modpack/normal/scripts/. But only if you have FTBTweaks

**Comment by DaNeo61** [comment]
I had FTBTweaks, FTBLib and FTBUtil installed all on the newsest version i tested the scripts everywhere 

evertime i connected on the server the recipes was reseted but only visual not technical so even if you wanted to craft them with the visual recipe i wont work only with the zs recipe.

I just downgraded to forge 1558 and ftblib, ftbutil and ftbtweaks versions like infinity evolved.
Currently its working fine i just wanted to get sure to have everywhere the newest versions.
