### ISSUE TITLE
/list command incorrectly returns player numbers in rcon

### ISSUE THREAD

**Issue by rufjame** [LatvianModder/FTBLib#24]
When I have FTBLib installed, the /list command in rcon shows  "Players currently online: [ 0 ]"
In the server console when a player is online i get:  "Players currently online: [ 1 ]"

When FTBLib is not installed (both console and rcon) : "There are 0/20 players online" or "There are 1/20 players online"

**Comment by LatvianModder** [comment]
Will simply remove /list override

**Comment by LatvianModder** [comment]
Fixed in pre2
