### ISSUE TITLE
What is with this giant line that keeps being spammed in my console.

### ISSUE THREAD

**Issue by CrazyMonkeyMcgee** [LatvianModder/FTBLib#29]
Every minute or so I am getting a giant line that fills my console dis allowing me to look back at things. It looks like its happening when FTBLib is saving player and world data.
An example of the mentioned spam found [here](https://gist.github.com/CrazyMonkeyMcgee/2b0fa4a5f2a25fd23ed2c63948873e2e).

**Comment by LatvianModder** [comment]
Derp. Must have forgotten to remove that from console. It just prints every time world is saved

**Comment by CrazyMonkeyMcgee** [comment]
when can i expect an update that removes this print
