### ISSUE TITLE
Any server-side config GUI kicks player

### ISSUE THREAD

**Issue by QwiBeck** [LatvianModder/FTBLib#33]
When entering **/ftb edit_config** or pressing **My server config** button on GUI
Server ceeps running.

**Comment by Alaberti** [comment]
As a server admin, is there a way to manually edit the config in the meantime while the fix is pending?

**Comment by QwiBeck** [comment]
Manualy it works fine. Just bugreport)

**Comment by LatvianModder** [comment]
@Alaberti yes, all configs can be edited manually, by using /whatever_command <press Tab to find config entry ID> <enter value in json format>
