### ISSUE TITLE
Packmodes in 1.9+

### ISSUE THREAD

**Issue by OscarXcore** [LatvianModder/FTBLib#40]
The packmodes in 1.9+ are not able to be set, in the matter that when the packmodes.json is set with modes and what not, and a client config reload/client restart/server config reload happens, the file is set back to the default config, as well as the reload ignoring read-only flags. I looked a bit into it and it seemed to run the createDefaults function every time the reload handler was triggered so instead of checking for custom edits then doing something with them, rather resetting the file no matter the configuration. If something can be looked into this, that would be awesome! Thanks!

**Comment by LatvianModder** [comment]
Yeah im rewriting it to load only once during startup, and not on every reload event. See https://github.com/LatvianModder/FTBLib/commit/9c048357271413d07324803458892b45cf21dab0

**Comment by OscarXcore** [comment]
Ahh awesome! Great to see that it is being fixed! I was working on making something work with Progression but it just disables whole item recipes instead of being able to disable certain ones. Either way, this will be a lot better!

**Comment by LatvianModder** [comment]
Should be fixed
