### ISSUE TITLE
Crash on server-start-up?

### ISSUE THREAD

**Issue by Beanius** [LatvianModder/FTBLib#45]
https://gist.github.com/Beanius/ae27392c4f79239be7a35e27080b9e36

**Comment by LatvianModder** [comment]
Uh oh

**Comment by Beanius** [comment]
B)

**Comment by CelticChristoph** [comment]
Any word on this? Getting the same error myself on MC 1.10.2/Forge 12.18.3.2221.

I have no problem rolling back and waiting patiently if that's the preferred option at the moment! Thanks <3

**Comment by Rickydou** [comment]
Crash Start Up: FTBLib-1.10.2-3.2.7 / FTBUtilities-1.10.2-3.2.7 
Forge 12.18.3.2221 ;)

**Comment by LatvianModder** [comment]
Did 3.2.8 fix it?

**Comment by Monsterrat25** [comment]
Was able to replicate same crash with version 3.2.7 on Forge 12.18.3.2185.
Tried the updated version 3.2.8 and experienced this crash on startup now https://gist.github.com/Monsterrat25/76d507e63e4d207872b383d649860206

**Comment by Rickydou** [comment]
Crash Start Up: FTBLib-1.10.2-3.2.8 / FTBUtilities-1.10.2-3.2.8
https://gist.github.com/Rickydou/3c01ab55e82aa55f35aece5566960da8
Forge 12.18.3.2221 ;)

**Comment by Beanius** [comment]
I guess i'm getting the same crashes everyone else are getting with 3.2.8.
https://gist.github.com/Beanius/ee3c37f2a913b37c6e7fc92f03af0827
B)

**Comment by LatvianModder** [comment]
Darn me! Why do I never click "Launch Server"! |:( I was actually in hurry this morning, so I didn't have time for testing, I hope I can fix this in evening

**Comment by Rickydou** [comment]
No stress .. version FTBLib-1.10.2-3.2.3 for now and super for the reaction :)

**Comment by LatvianModder** [comment]
Does 3.2.9 fix this?

**Comment by Rickydou** [comment]
Works 100% .. Remains to know the internal work ;)

**Comment by OrdinatorStouff** [comment]
I was having the same issues as the others but 3.2.9 is now working for me as well. Server starts and client can connect and load into the server fine with no crashes.

**Comment by Beanius** [comment]
seems to be working B)
