### ISSUE TITLE
[1.7.10] Modes

### ISSUE THREAD

**Issue by Xaikii** [LatvianModder/FTBLib#46]
Hey,
just wanted to ask if it possible to define the cfg per mode, so if I change the mode with /ftb_mode set x, and there is an other cfg in the mode file, that it will overwrite it

**Comment by LatvianModder** [comment]
a) Not gonna happen, because 1.7.10
b) This is likely not possible anyway, because those configs are loaded once, and most mods cache their values, etc. Basically, only recipes can be changed because they are reloaded every time world is loaded
