### ISSUE TITLE
NPE for LMServerUtils.isOP Call

### ISSUE THREAD

**Issue by everseeking** [LatvianModder/FTBLib#47]
Not my crash but looked like something new to bring up.

>java.lang.NullPointerException: Unexpected error
>at com.feed_the_beast.ftbl.lib.util.LMServerUtils.isOP(LMServerUtils.java:212)

* [Report](http://pastebin.com/j7a6sbA0)
* [Thread](https://www.reddit.com/r/FeedTheBeastCrashes/comments/5usa1d/player_randomly_dropping_from_server/)

Details
* Direwolf20 Modpack v1.6.0
* FTBLib-1.10.2-3.3.0.jar
* FTBUtilities-1.10.2-3.3.1.jar

FTB Lib issue or EnderIO issue with using Forge's Permission API?

**Comment by LatvianModder** [comment]
Ender IO, but that will be fixed from FTBLib side too

**Comment by LatvianModder** [comment]
See https://github.com/LatvianModder/FTBUtilities/issues/362

**Comment by LatvianModder** [comment]
Fixed in 3.4.0+
