### ISSUE TITLE
This or FTBUtils is causing crashes with my quarry.

### ISSUE THREAD

**Issue by TheUnderTaker11** [LatvianModder/FTBLib#52]
So I have a mod called Kitchen Sink, and in that mod I have a quarry block. When that quarry is used along with this mod and/or FTB Utils, [this crash happens](https://pastebin.com/JJ3uBTMA).
I don't know if it is my fault or the fault of one of those mods not doing a null check somewhere, but if you know something I'm doing wrong in my quarry don't hesitate to tell me.
[This is a link to my quarry class](https://github.com/TheUnderTaker11/KitchenSink/blob/MC-1.10.2/src/main/java/com/theundertaker11/kitchensink/ksblocks/quarry/KSTileEntityQuarryBlock.java)   

Basically I make a fake player name and null ID using these two lines
`private final String FAKE_PLAYER_NAME = "[KitchenSink]";`
`private final UUID FAKE_PLAYER_ID = null;`   
Then I create the EntityPlayerMP using 
`EntityPlayerMP fakeplayer = FakePlayerFactory.get((WorldServer) worldObj, new GameProfile(FAKE_PLAYER_ID, FAKE_PLAYER_NAME));`   
And lastly I use these lines to create a break block event and check if it got cancelled.
`BreakEvent event = new BreakEvent(this.getWorld(), blockPos, stateToMine, fakeplayer);`
`MinecraftForge.EVENT_BUS.post(event);`
`if(event.getResult() == Result.ALLOW)`   
Then it should go without saying I do the code that breaks the block and such inside the if statment.

Hopefully that is enough information to figure out what the problem is. If I should move this to FTB Utils github issue section I will do that.

Forge 12.18.3.2281
FTBLib version 1.1x-3.5.4
FTBUtil version 1.1x-3.5.4

**Comment by LatvianModder** [comment]
You Never use null as UUID. Do something like
```private final UUID FAKE_PLAYER_ID = UUID.nameUUIDFromBytes(FAKE_PLAYER_NAME.getBytes());```

**Comment by TheUnderTaker11** [comment]
It says you can leave the name or uuid null, but both both, so I did just that. I'll try changing that when I get home.

**Comment by TheUnderTaker11** [comment]
Doing that prevented the crash, thank you.
