### ISSUE TITLE
FTBLib replaces Quark blocks and items with random IDs from the same mod when the server starts up

### ISSUE THREAD

**Issue by HenrikoMagnifico** [LatvianModder/FTBLib#59]
FTBLib replaces Quark blocks and items with random IDs from the same mod when the server starts up. This has been confirmed to be caused by FTBLib-4.0.0.jar on the latest version of Forge (1.12 - 14.21.0.2328). It does not affects blocks from other mods. The bug does not affect blocks from vanilla Minecraft either.

**Comment by LatvianModder** [comment]
Do you have any crash reports or something pointing to FTBLib?
