### ISSUE TITLE
New reload command conflicts with Cauldron

### ISSUE THREAD

**Issue by NEXUS2345** [LatvianModder/FTBLib#6]
The recent change of the command from /ftb_reload to /reload conflicts with the spigot/cauldron command which basically means that many major servers cannot use the command at the moment. Changing the command back in my opinion would be the best option.

**Comment by phit** [comment]
in the local folder, edit the ftblib.json
change this line

      "reload": "reload",

to

      "reload": "ftb_reload",

**Comment by LatvianModder** [comment]
Yes, that's exactly why I added a config for it :)
