### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by HenrikoMagnifico** [LatvianModder/FTBLib#63]
Using FTBLib and FTBUtilties 4.0.3 on Forge-1.12-14.21.1.2397
https://pastebin.com/sj8S64wR

**Comment by LatvianModder** [comment]
I dont get it,this method exists for me in DevEnv

**Comment by PrinceApache** [comment]
Got the same issue, https://pastebin.com/DfNUutve

**Comment by LatvianModder** [comment]
Yeah, I can recreate it too. I will most likely release 4.0.4 to fix this by removing that line

**Comment by PrinceApache** [comment]
ETA on when?

**Comment by LatvianModder** [comment]
Right now. Found a fix

**Comment by LatvianModder** [comment]
On CurseForge in a bit, but available here http://mods.latmod.com/FTBLib/4.0.4/
