### ISSUE TITLE
Error When Accessing Server Info

### ISSUE THREAD

**Issue by V3xatious** [LatvianModder/FTBLib#64]
Hello!

So with everything running very smoothly. (Chunk claiming, anti-grief, teams, ect all briefly tested and working well) the only thing I've bumped into is clicking on the "Server Info" button.  

I am running Forge 2400 on both the server and my client, as well as FTBLib 4.0.4 and FTBUtilities 4.0.3.

The exact error message reads "An unknown error occurred while attempting to perform this command."
When looking at the debug console through my virtual server, I see this.

`12:36:57  [Warn] Couldn't process command: ftb server_infojava.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n	at treechopper.common.command.TCHCommand.func_71518_a(TCHCommand.java:35) ~[TCHCommand.class:?]	at com.feed_the_beast.ftbu.ranks.CmdOverride.func_71518_a(CmdOverride.java:58) ~[CmdOverride.class:?]	at com.feed_the_beast.ftbu.ServerInfoPage.addCommandUsage(ServerInfoPage.java:209) ~[ServerInfoPage.class:?]	at com.feed_the_beast.ftbu.ServerInfoPage.getPageForPlayer(ServerInfoPage.java:166) ~[ServerInfoPage.class:?]	at com.feed_the_beast.ftbu.cmd.CmdServerInfo.func_184881_a(CmdServerInfo.java:25) ~[CmdServerInfo.class:?]	at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.java:70) ~[CmdOverride.class:?]	at net.minecraftforge.server.command.CommandTreeBase.func_184881_a(CommandTreeBase.java:149) ~[CommandTreeBase.class:?]	at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.java:70) ~[CmdOverride.class:?]	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?] at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:948) [oy.class:?]	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:927) [oy.class:?]	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_102]	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_102]	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?]	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391) [nx.class:?]	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]`

Hopefully I haven't oversighted anything and wasted your time.
Thanks again for all the work you put into the most essential Forge mod.

EDIT: To add, this is the "server_info": section in my config.json folder, if it helps.
```
    "max_leaderboard_size": 250,
    "server_info": {
      "admin_quick_access": true,
      "difficulty": true,
      "mode": true
    },
```

**Comment by LatvianModder** [comment]
Not my error, `treechopper.common.command.TCHCommand.func_71518_a`, report to Tree Chopper

**Comment by V3xatious** [comment]
Whoops. My eyes skipped over that. Thank you. I'll take this over to their github.
