### ISSUE TITLE
[1.11.2] Errors, lag and console spam when looking at some objects lacking tooltips

### ISSUE THREAD

**Issue by cragrim** [LatvianModder/FTBLib#68]
#### Issue Description:
When looking at some objects like the Illumination Wand lights from Not Enough Wands and Moonstone Ore from ExtraUtils2 the client lags and the console is filled with tooltip errors. 

I dont know which mod is at fault but TehNut developer of Hwyla (continued fork of Waila) redirected me here from:
https://github.com/TehNut/HWYLA/issues/81

Appreciate any help or assistance :)
Best Regards

#### Description
The console quickly gets overflowed and the log gets several MB big. This makes debugging difficult unless caught in the act. As you play the log file gets larger and larger and causes additional slowdowns eventually freezing the client. Client runs fine again after a complete restart of Minecraft.

#### Gif animation
http://i.imgur.com/EsqPPjh.gif
![Gif video](http://i.imgur.com/EsqPPjh.gif)
http://i.imgur.com/5mygW0P.gif
![Moonstone error](http://i.imgur.com/5mygW0P.gif)

#### Error log 
Looking at the Illumination wand block
https://paste.ee/p/34s1J

Looking at moonstone ore:
https://paste.ee/p/EICKU

Error log from looking at the block without OptiFine and Foamfix
https://paste.ee/p/pFslr

#### What happens:
Lag and console tooltip errors.

#### What you expected to happen:
Nothing.

#### Steps to reproduce:

1. Place light with Illumination Wand
2. Look at the light
3. See error.

#### Affected Versions:
- FTBLib: FTBLib-1.1x-3.6.5.jar
- Hwyla: Hwyla-1.8.17-B31_1.11.jar
- Minecraft: 1.11.2
- Forge: forge-1.11.2-13.20.1.2391
- Not enough wands: notenoughwands-1.1x-1.5.5.jar
- ExtraUtils2: extrautils2-1.11.2-1.4.4.jar

#### Possible Conflicting Mods (Provide their version, as well)
I tried without the usual suspects OptiFine and FoamFix but it appears to be a conflict with some other mods. Still happens the same without them.

**Complete mod list:**
https://paste.ee/p/sIeiF

#### I made previous issues at Waila Harvestability, Not Enough Wands and Hwyla trying to narrow down this issue.
https://github.com/squeek502/WailaHarvestability/issues/58
https://github.com/romelo333/notenoughwands/issues/62
https://github.com/TehNut/HWYLA/issues/81

**Comment by LatvianModder** [comment]
1.11 won't get updates, only 1.12+ but it should disappear if you disable Item Ore Names in Client Config

**Comment by cragrim** [comment]
Thank you for the response!!!
Where do I find that in the configs? I ran a search using notepad++ for "Item Ore Names" in all my config files but couldn't find it.

Could you please elaborate? Appreciate the assistance !!!
Thanks

**Comment by cragrim** [comment]
For future reference if you have this issue this is how you solve it for 1.11.2

Edit the config in the local folder in your client and locate:
**minecraft\local\client_config.json**
Change ftblib settings for **Item Ore Names** to false i.e.:
**"item_ore_names": false**

Cheers!
